config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :docs

  get 'docs/:id/export_word' => 'docs#export_word', :as => :download

  authenticated :user do
    root 'docs#index', as: "authenticated_root"
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
    @docs = Doc.where(user_id: current_user).order("updated_at DESC")
  end

  def show
  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)

    if @doc.save
      redirect_to @doc, notice: 'Document Created Successfully.', time: 1500
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc, notice: 'Document Updated Successfully.', time: 1500
    else
      render 'edit'
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path, notice: 'Document Deleted Successfully.', time: 1500
  end

  def export_word
    find_doc

    html = MarkdownToWord.convert(@doc.content)
    send_file "app/assets/downloads/#{@doc.title}.docx",
      :type =>
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      :disposition => 'attachment'
  end

  private

  def find_doc
    @doc = Doc.find(params[:id])
  end

  def doc_params
    params.require(:doc).permit(:title, :content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      superscript: true,
      autolink: true,
      lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  = f.input :title
  = f.input :content, :input_html => {:rows => 25}
  = f.button :button, class: "button" do
    %i.far.fa-save.fa-2x

app/views/docs/edit.html.haml
.wrapper_with_padding
  %h1 Edit Document

  = render 'form'

  = link_to 'Cancel', doc_path

app/views/docs/index.html.haml
.wrapper_with_padding
  #docs.clearfix
    - unless @docs.blank?
      - @docs.each do |doc|
        %a{ href: (url_for [doc]) }
          .doc
            %p.title= doc.title
            %p.date= "Last Updated: #{time_ago_in_words(doc.updated_at)}"
    - else
      %h2 Create Document!
      %p All your files are belong to us. Organized, always.
      %button= link_to 'Create Document', new_doc_path

app/views/docs/new.html.haml
.wrapper_with_padding
  %h1 New Document

  = render 'form'

app/views/docs/show.html.haml
.wrapper_with_padding
  #doc_show
    %h1.title= @doc.title
    %p.content= markdown @doc.content

    .buttons
      = link_to edit_doc_path(@doc), class: "button" do
        %i.fas.fa-edit.fa-lg

      = link_to '', class: "button" do
        %i.fas.fa-file-word.fa-lg

      = link_to '', class: "button" do
        %i.fas.fa-file-pdf.fa-lg

      = link_to doc_path(@doc), method: :delete, data: { confirm: "Are you sure?" }, class: "button" do
        %i.fas.fa-trash-alt.fa-lg

app/views/layouts/application.html.haml
!!!
%html
%head
  %title FileBase | All your files are belong to us
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
%body
  %header
    .header_inner
      = link_to 'FileBase', root_path, id: "logo"

      = render 'shared/nav'

  = js add_gritter(flash[:notice], title: "FileBase Notification", sticky: false, time: 1500)
  = yield

app/views/shared/_nav.html.haml
%nav
  - if user_signed_in?
    = link_to new_doc_path do
      %i.fas.fa-file-alt.fa-2x

    = link_to '' do
      %i.fas.fa-info-circle.fa-2x

    = link_to destroy_user_session_path, method: :delete do
      %i.fas.fa-sign-out-alt.fa-2x

  - else
    = link_to new_user_session_path do
      %i.fas.fa-sign-in-alt.fa-2x

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 FileBase
    %p All your files are belong to us. Organized, always.
    %button= link_to "Register", new_user_registration_path

#testimonial
  .wrapper
    %p.quote "Much Wow!"
    %p.name - Doge
    %p.quote "FileBase brings peace to all the things."
    %p.name - M. Gandhi

#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 Syntax Highlighting & Markdown Support
        %p CSS, ERB, Go, HAML, HTML, JSON, Java, JavaScript
        %p PHP, Python, Ruby, SQL, SASS, XML, YAML.
      .callout
        %h2 Document Everything With FileBase
        %p Processes, Code Snippets, Repeatable Tasks.
      .callout
        %h2 Export to PDF or Word
        %p Document format you need readily available!

#bottom_cta
  .wrapper
    %h2 Click here!
    %p Files are belong to us!
    %button= link_to "Join Now", new_user_registration_path